version: '3.12'

services:
  analyzer_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app/db:/app/db  # Монтируем локальную директорию с базой данных в контейнер
    depends_on:
      - cosmetics_db  # Эта строка больше не нужна, так как PostgreSQL не используется
    env_file:
        - .env
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  # Удаляем сервис для PostgreSQL, так как мы используем SQLite
  # cosmetics_db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  # postgres_data: # Это можно удалить, так как больше не используем PostgreSQL
